import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Image as ImageIcon } from 'lucide-react';
import { Theme } from '../types';
import { generateImage } from '../services/geminiService';

interface ImageCanvasProps {
  theme: Theme;
}

const ImageCanvas: React.FC<ImageCanvasProps> = ({ theme }) => {
  const [prompt, setPrompt] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleGenerateImage = async () => {
    if (!prompt.trim()) return;
    setIsLoading(true);
    setImageUrl('');
    setError('');
    try {
      const result = await generateImage(prompt);
      if (result) {
        setImageUrl(result);
      } else {
        setError('Could not generate image. The result was empty.');
      }
    } catch (err) {
      setError('An error occurred while generating the image.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="h-full flex flex-col p-4 md:p-8 overflow-auto">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: 'easeOut' }}
        className="w-full max-w-4xl mx-auto flex flex-col items-center"
      >
        <h2 className="text-2xl font-bold mb-6 text-center">Image Studio</h2>

        {/* Prompt Input */}
        <div className={`relative w-full rounded-3xl backdrop-blur-xl transition-all duration-300 mb-6 ${
          theme === 'dark'
            ? 'bg-slate-800/50 shadow-neumorphic-dark shadow-glass-inset-dark'
            : 'bg-white/30 shadow-neumorphic-light shadow-glass-inset-light'
        }`}>
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter') handleGenerateImage(); }}
            placeholder="Describe the image you want to create..."
            className={`w-full h-14 pl-6 pr-20 py-4 bg-transparent border-none focus:ring-0 resize-none outline-none
              ${theme === 'dark' ? 'text-slate-200 placeholder:text-slate-500' : 'text-slate-800 placeholder:text-slate-400'}`}
            disabled={isLoading}
          />
          <motion.button
            onClick={handleGenerateImage}
            disabled={isLoading || !prompt.trim()}
            className="absolute right-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full flex items-center justify-center
              bg-gradient-to-br from-[var(--primary-color)] to-[var(--accent-color)] text-white disabled:opacity-50 transition-opacity"
            whileHover={{ scale: 1.1, rotate: 15 }}
            whileTap={{ scale: 0.9, rotate: 0 }}
            style={{boxShadow: '0 0 20px -5px var(--primary-color)'}}
          >
             {isLoading ? <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div> : <ImageIcon size={20} />}
          </motion.button>
        </div>

        {/* Image Display */}
        <div className={`w-full aspect-square max-w-lg rounded-3xl backdrop-blur-xl flex items-center justify-center p-4 transition-all duration-300 ${
           theme === 'dark'
            ? 'bg-slate-900/60 shadow-glass-inset-dark'
            : 'bg-white/40 shadow-glass-inset-light'
        }`}>
            {isLoading && (
                 <div className="flex flex-col items-center gap-4 text-slate-400">
                    <div className="w-12 h-12 border-4 border-slate-400 border-t-transparent rounded-full animate-spin"></div>
                    <p>Creating masterpiece...</p>
                 </div>
            )}
            {error && <p className="text-red-400 text-center">{error}</p>}
            {!isLoading && !error && imageUrl && (
                <motion.img 
                    src={imageUrl} 
                    alt="Generated by AI" 
                    className="w-full h-full object-contain rounded-2xl"
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.5 }}
                />
            )}
            {!isLoading && !error && !imageUrl && (
                 <div className="flex flex-col items-center gap-4 text-slate-400">
                    <ImageIcon size={64} strokeWidth={1} />
                    <p>Your generated image will appear here</p>
                 </div>
            )}
        </div>
      </motion.div>
    </div>
  );
};

export default ImageCanvas;
